import java.time.LocalDate;

public class Report {
    private String reportID;
    private LocalDate generatedDate;
    private Admin generatedBy;
    private Canteen canteen;
    private LocalDate startDate;
    private LocalDate endDate;

    public Report(Admin admin, Canteen canteen) {
        this.reportID = "RPT" + System.currentTimeMillis();
        this.generatedDate = LocalDate.now();
        this.generatedBy = admin;
        this.canteen = canteen;
        this.startDate = null;
        this.endDate = null;
    }

    public Report(Admin admin, Canteen canteen, LocalDate start, LocalDate end) {
        this.reportID = "RPT" + System.currentTimeMillis();
        this.generatedDate = LocalDate.now();
        this.generatedBy = admin;
        this.canteen = canteen;
        this.startDate = start;
        this.endDate = end;
    }

    public void printReport() {
        System.out.println("\n=======================================================");
        System.out.println("   ANALYTICS REPORT : " + canteen.getCanteenName().toUpperCase());
        System.out.println("=======================================================");
        System.out.println("Report ID    : " + reportID);
        System.out.println("Generated By : " + generatedBy.getFullName() + " (Admin ID: " + generatedBy.getAdminID() + ")");
        System.out.println("Date         : " + generatedDate);

        if (startDate != null) {
            System.out.println("Period       : " + startDate + " to " + endDate);
        } else {
            System.out.println("Period       : All time");
        }
        System.out.println("-------------------------------------------------------");

        int totalRes = canteen.getTotalReservations(startDate, endDate);
        double avgScore = canteen.getAverageScore(startDate, endDate);
        String popularTable = canteen.getMostPopularTable(startDate, endDate);
        String peakHour = canteen.getPeakHour(startDate, endDate);

        System.out.println("Total Reservations : " + totalRes + " times");
        System.out.printf("Average Rating     : %.2f / 5.0%n", avgScore);
        System.out.println("Most Popular Table : Table " + popularTable);
        System.out.println("Peak Booking Hours : " + peakHour);
        System.out.println("=======================================================\n");
    }

    public String getReportID() { return reportID; }
    public LocalDate getGeneratedDate() { return generatedDate; }
    public Admin getGeneratedBy() { return generatedBy; }
    public Canteen getCanteen() { return canteen; }
}