import java.sql.Date;

public class Report {
    private String reportID;
    private Date generatedDate;
    private Admin generatedBy;
    private Canteen canteen;

    public Report(Admin admin, Canteen canteen) {
        this.reportID = "REP" + System.currentTimeMillis();
        this.generatedDate = new Date(System.currentTimeMillis()); 
        this.generatedBy = admin;
        this.canteen = canteen;
    }

    public void printReport() {
        System.out.println("\n=======================================================");
        System.out.println("   ANALYTICS REPORT : " + canteen.getCanteenName().toUpperCase());
        System.out.println("=======================================================");
        
        System.out.println("Report ID    : " + this.reportID);
        System.out.println("Generated By : " + this.generatedBy.getFullName() + " (Admin ID: " + this.generatedBy.getAdminID() + ")");
        System.out.println("Date         : " + this.generatedDate.toString());
        System.out.println("-------------------------------------------------------");

        int totalRes = DatabaseManager.getTotalReservationsCount();
        double avgScore = DatabaseManager.getAverageScore();
        String popularTable = DatabaseManager.getMostPopularTable();
        String peakHour = DatabaseManager.getPeakHour(); 
        
        System.out.println("Total Reservations   : " + totalRes + " times");
        System.out.printf("Average Rating       : %.2f / 5.0\n", avgScore);
        System.out.println("Most Popular Table   : Table " + popularTable);
        System.out.println("Peak Booking Hours   : " + peakHour);

        System.out.println("=======================================================\n");
    }
    public String getReportID() { return reportID; }
    public Date getGeneratedDate() { return generatedDate; }
    public Admin getGeneratedBy() { return generatedBy; }
    public Canteen getCanteen() { return canteen; }
}